/**
 * Generates src/data/emojis.js from emoji-datasource-apple/emoji.json
 * Run: node scripts/generate-emojis.js
 */
const data = require('../node_modules/emoji-datasource-apple/emoji.json');
const fs   = require('fs');
const path = require('path');

// Category order matching standard emoji keyboard
const CAT_ORDER = [
  'Smileys & Emotion',
  'People & Body',
  'Animals & Nature',
  'Food & Drink',
  'Travel & Places',
  'Activities',
  'Objects',
  'Symbols',
  'Flags',
];

const CAT_ICONS = {
  'Smileys & Emotion': '😀',
  'People & Body':     '👋',
  'Animals & Nature':  '🐶',
  'Food & Drink':      '🍔',
  'Travel & Places':   '✈️',
  'Activities':        '⚽',
  'Objects':           '💡',
  'Symbols':           '❤️',
  'Flags':             '🏳️',
};

// Convert unified codepoint string → actual emoji character
function unifiedToChar(unified) {
  return unified.split('-').map(cp => String.fromCodePoint(parseInt(cp, 16))).join('');
}

// Build map of category → sorted emojis
const catMap = {};
CAT_ORDER.forEach(c => catMap[c] = []);

// Filter: only include emojis that have Apple image (has_img_apple)
const valid = data
  .filter(e => e.has_img_apple)
  .sort((a, b) => (a.sort_order || 9999) - (b.sort_order || 9999));

for (const entry of valid) {
  const cat = entry.category;
  if (!catMap[cat]) continue;

  const baseEmoji = unifiedToChar(entry.unified);
  const name = (entry.short_name || entry.name || '').replace(/_/g, ' ').toLowerCase();

  catMap[cat].push({ e: baseEmoji, n: name });

  // Add skin tone variants if any
  if (entry.skin_variations) {
    for (const [, variant] of Object.entries(entry.skin_variations)) {
      if (!variant.has_img_apple) continue;
      const varEmoji = unifiedToChar(variant.unified);
      const tone = variant.unified.toLowerCase().includes('1f3fb') ? 'light' :
                   variant.unified.toLowerCase().includes('1f3fc') ? 'medium-light' :
                   variant.unified.toLowerCase().includes('1f3fd') ? 'medium' :
                   variant.unified.toLowerCase().includes('1f3fe') ? 'medium-dark' :
                   variant.unified.toLowerCase().includes('1f3ff') ? 'dark' : 'variant';
      catMap[cat].push({ e: varEmoji, n: `${name} ${tone} skin` });
    }
  }
}

// Build output
const categories = CAT_ORDER
  .filter(c => catMap[c].length > 0)
  .map(c => ({
    label: c,
    icon:  CAT_ICONS[c] || catMap[c][0]?.e || '❓',
    emojis: catMap[c],
  }));

const totalCount = categories.reduce((s, c) => s + c.emojis.length, 0);
console.log(`Categories: ${categories.length}`);
categories.forEach(c => console.log(`  ${c.label}: ${c.emojis.length}`));
console.log(`Total: ${totalCount} emojis`);

const out = `// Auto-generated by scripts/generate-emojis.js
// Source: emoji-datasource-apple (Emoji 15.1 — ${totalCount} emojis)
// Do not edit manually. Run: node scripts/generate-emojis.js

const EMOJI_DATA = ${JSON.stringify(categories, null, 0)
  .replace(/\{"label":/g, '\n  {\n    "label":')
  .replace(/,"icon":/g, ', "icon":')
  .replace(/,"emojis":\[/g, ',\n    "emojis": [\n      ')
  .replace(/\},\{"e":/g, '},\n      {"e":')
  .replace(/\]\}/g, '\n    ]\n  }')
};

export default EMOJI_DATA;
`;

const outPath = path.join(__dirname, '../src/data/emojis.js');
fs.writeFileSync(outPath, out, 'utf8');
console.log(`\nWritten to ${outPath}`);
